// Code generated by go generate; DO NOT EDIT.
// Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.

package lambda

import (
	"context"
  "encoding/json"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda/handlertrace"
)

// NewHandlerChimeBotEvent is used to process ChimeBotEvent types.
func NewHandlerChimeBotEvent(handler func(context.Context, events.ChimeBotEvent) error) Handler {
	return lambdaHandler(func(ctx context.Context, payload []byte) (interface{}, error) {
		trace := handlertrace.FromContext(ctx)

		var e events.ChimeBotEvent
		if err := json.Unmarshal(payload, &e); err != nil {
			panic(err)
		}

		if trace.RequestEvent != nil {
			trace.RequestEvent(ctx, e)
		}
		
    return nil, handler(ctx, e)
	})
}