// Code generated by go generate; DO NOT EDIT.
// Copyright 2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.

package lambda

import (
	"context"
  "encoding/json"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda/handlertrace"
)

// NewHandlerCodeCommitEvent is used to process CodeCommitEvent types.
func NewHandlerCodeCommitEvent(handler func(context.Context, events.CodeCommitEvent)) Handler {
	return lambdaHandler(func(ctx context.Context, payload []byte) (interface{}, error) {
		trace := handlertrace.FromContext(ctx)

		var e events.CodeCommitEvent
		if err := json.Unmarshal(payload, &e); err != nil {
			panic(err)
		}

		if trace.RequestEvent != nil {
			trace.RequestEvent(ctx, e)
		}
		
    handler(ctx, e)

    return nil, nil
	})
}